apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t4n7td2oc-python
  janus-idp.io/tekton: t4n7td2oc-python
  backstage.io/kubernetes-id: t4n7td2oc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t4n7td2oc-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
