apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t4n7td2oc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t4n7td2oc-python 
  name: t4n7td2oc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t4n7td2oc-python 
